# Generated by Django 3.1.3 on 2020-11-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0005_pessoa_bairro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='bairro',
            field=models.CharField(max_length=50),
        ),
    ]
